#!/usr/bin/env python3
import hashlib
import subprocess
import sys


def parse_nm_symbol(nm_bin: str, elf_path: str, sym: str) -> int:
    out = subprocess.check_output([nm_bin, "-n", elf_path], text=True, errors="strict")
    for line in out.splitlines():
        parts = line.strip().split()
        if len(parts) >= 3 and parts[2] == sym:
            return int(parts[0], 16)
    raise RuntimeError(f"symbol not found: {sym}")


def digest_c_initializer(digest: bytes) -> str:
    return "{ " + ", ".join(f"0x{b:02X}" for b in digest) + " }"


def main() -> int:
    if len(sys.argv) < 4 or len(sys.argv) > 6:
        print("Usage: gen_kernel_manifest.py <kernel8.elf> <kernel8.img> <out-header> [nm-bin] [signer-key-id]")
        return 1

    elf_path = sys.argv[1]
    img_path = sys.argv[2]
    out_header = sys.argv[3]
    nm_bin = sys.argv[4] if len(sys.argv) >= 5 else "aarch64-linux-gnu-nm"
    signer_key_id = int(sys.argv[5], 0) if len(sys.argv) >= 6 else 0x00000001

    text_start = parse_nm_symbol(nm_bin, elf_path, "__kernel_text_start")
    ro_end = parse_nm_symbol(nm_bin, elf_path, "__kernel_rodata_end")
    if ro_end <= text_start:
        raise RuntimeError("invalid section bounds")

    load_base = 0x80000
    off0 = text_start - load_base
    off1 = ro_end - load_base
    if off0 < 0 or off1 < 0:
        raise RuntimeError("symbol below kernel load base")

    with open(img_path, "rb") as f:
        blob = f.read()

    if off1 > len(blob):
        raise RuntimeError("image too small for computed section range")

    digest = hashlib.sha256(blob[off0:off1]).digest()
    digest_hex = "".join(f"{b:02X}" for b in digest)
    digest_init = digest_c_initializer(digest)

    header = f"""#ifndef KERNEL_MANIFEST_AUTOGEN_H
#define KERNEL_MANIFEST_AUTOGEN_H

// Auto-generated by tools/gen_kernel_manifest.py
// Source region: __kernel_text_start .. __kernel_rodata_end
// Measured digest: {digest_hex}

#define KERNEL_MANIFEST_VERSION       1u
#define KERNEL_MANIFEST_SIGNER_KEY_ID 0x{signer_key_id:08X}u
#define KERNEL_MANIFEST_SIG_ALG       QOS_SIG_ALG_DIGEST_ONLY
#define KERNEL_MANIFEST_FLAGS         QOS_PROG_FLAG_SHA256
#define KERNEL_MANIFEST_SIG_LEN       0u
#define KERNEL_MANIFEST_DIGEST_INIT   {digest_init}
#define KERNEL_MANIFEST_SIGNATURE_INIT {{0}}

#endif
"""

    with open(out_header, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)

    print("Measured kernel digest (text..rodata):")
    print(digest_hex)
    print(f"Wrote header: {out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

