#!/usr/bin/env python3
import os
import subprocess
import sys
import tempfile

QOS_PQ_MAX_PUBKEY_BYTES = 2592  # ML-DSA-87 upper bound


def pubkey_from_private_pem(openssl_bin: str, priv_pem: str) -> bytes:
    with tempfile.TemporaryDirectory(prefix="qos_pub_") as td:
        pub_der = os.path.join(td, "pub.der")
        subprocess.check_call([
            openssl_bin, "pkey",
            "-in", priv_pem,
            "-pubout",
            "-outform", "DER",
            "-out", pub_der,
        ])
        with open(pub_der, "rb") as f:
            der = f.read()
    # Ed25519 SubjectPublicKeyInfo DER prefix:
    # 30 2a 30 05 06 03 2b 65 70 03 21 00 || 32-byte pubkey
    prefix = bytes.fromhex("302A300506032B6570032100")
    if len(der) != len(prefix) + 32 or not der.startswith(prefix):
        raise RuntimeError("unexpected Ed25519 public key DER format")
    return der[len(prefix):]


def bytes_init(b: bytes) -> str:
    return "{ " + ", ".join(f"0x{x:02X}" for x in b) + " }"


def read_pq_pubkey(path: str) -> bytes:
    with open(path, "rb") as f:
        data = f.read()
    if len(data) > QOS_PQ_MAX_PUBKEY_BYTES:
        raise RuntimeError(
            f"unexpected PQ public key length for {path}: "
            f"{len(data)} (max {QOS_PQ_MAX_PUBKEY_BYTES})"
        )
    if len(data) not in (1312, 1952, 2592):
        raise RuntimeError(
            f"unexpected PQ public key length for {path}: {len(data)} "
            f"(expected ML-DSA-44/65/87 public key length)"
        )
    return data


def pad_right(data: bytes, size: int) -> bytes:
    if len(data) > size:
        raise RuntimeError("pad_right overflow")
    if len(data) == size:
        return data
    return data + bytes(size - len(data))


def main() -> int:
    if len(sys.argv) < 2 or len(sys.argv) > 7:
        print(
            "Usage: gen_trust_keys_header.py <out-header> "
            "[admin-priv-pem] [dev-priv-pem] [openssl-bin] [admin-pq-pub-bin] [dev-pq-pub-bin]"
        )
        return 1

    out_header = sys.argv[1]
    admin_priv = sys.argv[2] if len(sys.argv) >= 3 else ""
    dev_priv = sys.argv[3] if len(sys.argv) >= 4 else ""
    openssl_bin = sys.argv[4] if len(sys.argv) >= 5 else "openssl"
    admin_pq_pub_path = sys.argv[5] if len(sys.argv) >= 6 else ""
    dev_pq_pub_path = sys.argv[6] if len(sys.argv) >= 7 else ""

    admin_pub = bytes(32)
    dev_pub = bytes(32)
    admin_pq_pub = bytes()
    dev_pq_pub = bytes()

    if admin_priv:
        admin_pub = pubkey_from_private_pem(openssl_bin, admin_priv)
    if dev_priv:
        dev_pub = pubkey_from_private_pem(openssl_bin, dev_priv)
    if admin_pq_pub_path:
        admin_pq_pub = read_pq_pubkey(admin_pq_pub_path)
    if dev_pq_pub_path:
        dev_pq_pub = read_pq_pubkey(dev_pq_pub_path)

    admin_pq_len = len(admin_pq_pub)
    dev_pq_len = len(dev_pq_pub)
    admin_pq_pub_padded = pad_right(admin_pq_pub, QOS_PQ_MAX_PUBKEY_BYTES)
    dev_pq_pub_padded = pad_right(dev_pq_pub, QOS_PQ_MAX_PUBKEY_BYTES)

    text = f"""#ifndef TRUST_KEYS_AUTOGEN_H
#define TRUST_KEYS_AUTOGEN_H

// Auto-generated by tools/gen_trust_keys_header.py

#define TRUST_ADMIN_ED25519_PUBKEY_INIT {bytes_init(admin_pub)}
#define TRUST_DEV_ED25519_PUBKEY_INIT   {bytes_init(dev_pub)}

#define TRUST_ADMIN_PQ_PUBKEY_LEN {admin_pq_len}u
#define TRUST_DEV_PQ_PUBKEY_LEN   {dev_pq_len}u
#define TRUST_ADMIN_PQ_PUBKEY_INIT {bytes_init(admin_pq_pub_padded)}
#define TRUST_DEV_PQ_PUBKEY_INIT   {bytes_init(dev_pq_pub_padded)}

#endif
"""
    with open(out_header, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

    if admin_priv:
        print(f"Admin Ed25519 pubkey extracted from: {admin_priv}")
    else:
        print("Admin Ed25519 pubkey left as zero placeholder.")
    if dev_priv:
        print(f"Developer Ed25519 pubkey extracted from: {dev_priv}")
    else:
        print("Developer Ed25519 pubkey left as zero placeholder.")
    if admin_pq_pub_path:
        print(f"Admin PQ pubkey loaded from: {admin_pq_pub_path} ({admin_pq_len} bytes)")
    else:
        print("Admin PQ pubkey left as zero placeholder.")
    if dev_pq_pub_path:
        print(f"Developer PQ pubkey loaded from: {dev_pq_pub_path} ({dev_pq_len} bytes)")
    else:
        print("Developer PQ pubkey left as zero placeholder.")
    print(f"Wrote header: {out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
