#!/usr/bin/env python3
import os
import subprocess
import sys
import tempfile


def pubkey_from_private_pem(openssl_bin: str, priv_pem: str) -> bytes:
    with tempfile.TemporaryDirectory(prefix="qos_pub_") as td:
        pub_der = os.path.join(td, "pub.der")
        subprocess.check_call([
            openssl_bin, "pkey",
            "-in", priv_pem,
            "-pubout",
            "-outform", "DER",
            "-out", pub_der
        ])
        with open(pub_der, "rb") as f:
            der = f.read()
    # Ed25519 SubjectPublicKeyInfo DER prefix:
    # 30 2a 30 05 06 03 2b 65 70 03 21 00 || 32-byte pubkey
    prefix = bytes.fromhex("302A300506032B6570032100")
    if len(der) != len(prefix) + 32 or not der.startswith(prefix):
        raise RuntimeError("unexpected Ed25519 public key DER format")
    return der[len(prefix):]


def bytes_init(b: bytes) -> str:
    return "{ " + ", ".join(f"0x{x:02X}" for x in b) + " }"


def main() -> int:
    if len(sys.argv) < 2 or len(sys.argv) > 5:
        print("Usage: gen_trust_keys_header.py <out-header> [admin-priv-pem] [dev-priv-pem] [openssl-bin]")
        return 1

    out_header = sys.argv[1]
    admin_priv = sys.argv[2] if len(sys.argv) >= 3 else ""
    dev_priv = sys.argv[3] if len(sys.argv) >= 4 else ""
    openssl_bin = sys.argv[4] if len(sys.argv) >= 5 else "openssl"

    admin_pub = bytes(32)
    dev_pub = bytes(32)
    if admin_priv:
        admin_pub = pubkey_from_private_pem(openssl_bin, admin_priv)
    if dev_priv:
        dev_pub = pubkey_from_private_pem(openssl_bin, dev_priv)

    text = f"""#ifndef TRUST_KEYS_AUTOGEN_H
#define TRUST_KEYS_AUTOGEN_H

// Auto-generated by tools/gen_trust_keys_header.py

#define TRUST_ADMIN_ED25519_PUBKEY_INIT {bytes_init(admin_pub)}
#define TRUST_DEV_ED25519_PUBKEY_INIT   {bytes_init(dev_pub)}

#endif
"""
    with open(out_header, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)

    if admin_priv:
        print(f"Admin pubkey extracted from: {admin_priv}")
    else:
        print("Admin pubkey left as zero placeholder.")
    if dev_priv:
        print(f"Developer pubkey extracted from: {dev_priv}")
    else:
        print("Developer pubkey left as zero placeholder.")
    print(f"Wrote header: {out_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

